<?php 
/*******************************************************************************************
 * AdiInviter Pro 1.1 Stable Release by AdiInviter, Inc.                                   *
 *-----------------------------------------------------------------------------------------*
 *                                                                                         *
 * https://www.adiinviter.com                                                              *
 *                                                                                         *
 * Copyright © 2008-2014, AdiInviter, Inc. All rights reserved.                            *
 * You may not redistribute this file or its derivatives without written permission.       *
 *                                                                                         *
 * Support Email: support@adiinviter.com                                                   *
 * Sales Email: sales@adiinviter.com                                                       * 
 *                                                                                         *
 *-------------------------------------LICENSE AGREEMENT-----------------------------------*
 * 1. You are allowed to use AdiInviter Pro software and its code only on domain(s) for    * 
 *    which you have purchased a valid and legal license from www.adiinviter.com.          *
 * 2. You ARE NOT allowed to REMOVE or MODIFY the copyright text within the .php files     *
 *    themselves.                                                                          *
 * 3. You ARE NOT allowed to DISTRIBUTE the contents of any of the included files.         *
 * 4. You ARE NOT allowed to COPY ANY PARTS of the code and/or use it for distribution.    *
 ******************************************************************************************/
 
$adiinviter_services = array(
  'gmail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Gmail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'yahoo' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Yahoo',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'hotmail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Outlook',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'linkedin' => array(
    'avatar' => 1,
    'email' => 0,
    'id' => 1,
    'service' => 'LinkedIn',
    'service_type' => 'Social',
    'invitation' => 'social',
  ),
  'aol' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'AOL',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'twitter' => array(
    'avatar' => 1,
    'email' => 0,
    'id' => 1,
    'service' => 'Twitter',
    'service_type' => 'Social',
    'invitation' => 'social',
  ),
  'mail_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Mail.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'icloud' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'iCloud',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'gmx_net' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Gmx.net',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'freenet_de' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Freenet',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'arcor' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Arcor',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'libero' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Libero',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'virgilio' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Virgilio',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'mailchimp' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'MailChimp',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'excite_it' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Excite.it',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'tonline' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 't-online.de',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'email_it' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Email.it',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'sapo' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Sapo',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'fastmail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Fastmail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  /*'facebook' => array(
    'avatar' => 1,
    'email' => 1,
    'id' => 0,
    'service' => 'Facebook',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),*/
  'terra' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Terra',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'bol_com_br' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Bol.com.br',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'operamail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Operamail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'interia' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Interia',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'mynet' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Mynet',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'inbox' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Inbox',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'qip' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Qip.ru',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'mail_ru' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Mail.ru',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'rambler' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Rambler',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'yandex' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Yandex',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'pochta' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Pochta',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'freemail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Freemail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'netaddress' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'NetAddress',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'eventbrite' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Eventbrite',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'hushmail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Hushmail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'atlas' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Atlas',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'azet' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Azet',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'xing' => array(
    'avatar' => 1,
    'email' => 1,
    'id' => 0,
    'service' => 'Xing',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'orkut' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Orkut',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'aussiemail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Aussiemail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'techemail' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Techemail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'meta' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Meta',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'zoho_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Zoho.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'mail2world' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Mail2World',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'o2' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'O2',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'wpl' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'WPL',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'nextmail_ru' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'NextMail.ru',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'india' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'India',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'evite' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Evite',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'abv' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'ABV',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'mail_in' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Mail.in',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'rediff' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Rediff',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'web_de' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Web.de',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'clix_pt' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Clix.pt',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'lycos' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Lycos',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'iol_pt' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'iOL.pt',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'citromail_hu' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'CitroMail',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'onet_pl' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Onet',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'sina_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Sina',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'qq_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'qq',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'tom' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Tom.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'sohu' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Sohu.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'yeah' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Yeah',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'ost_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => '163.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'ots_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => '126.com',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'daum_net' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Daum',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'naver_com' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Naver',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'laposte' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Laposte',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'bsnl_in' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Bsnl.in',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'dataone_in' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Dataone.in',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'nz11' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'nz11',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'walla' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Walla',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'bigstring' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'BigString',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'hi5' => array(
    'avatar' => 1,
    'email' => 0,
    'id' => 1,
    'service' => 'Hi5',
    'service_type' => 'Social',
    'invitation' => 'social',
  ),
  'kincafe' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Kincafe',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'plaxo' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Plaxo',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'runbox' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Runbox',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
  'csv_inviter' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Contact File',
    'service_type' => 'CSV',
    'invitation' => 'email',
  ),
  'manual_inviter' => array(
    'avatar' => 0,
    'email' => 1,
    'id' => 0,
    'service' => 'Manually',
    'service_type' => 'Webmail',
    'invitation' => 'email',
  ),
);
?>