<?php

// DEFAULT OPTIONS ARRAY

$tempera_defaults = array(

"tempera_db" => "1.0",

"tempera_side"		=> "2cSr",
"tempera_sidewidth"	=> 900,
"tempera_sidebar"	=> 250,
"tempera_mobile"	=> "Enable",
"tempera_hcontain"	=> "",
"tempera_zoom"      => 0,

"tempera_frontpage"		=> "Enable",
"tempera_frontposts"	=> "Enable",
"tempera_frontpostscount" 		=> get_option('posts_per_page'), 
"tempera_frontpostsperrow" 		=> "2", 
"tempera_fpsliderwidth"			=> "1150",
"tempera_fpsliderheight"		=> "400",
"tempera_fpslideranim"	=> "random",
"tempera_fpslidertime"	=> "750",
"tempera_fpsliderpause"	=> "5000",
"tempera_fpslidernav"	=> "Bullets",
"tempera_fpsliderarrows"		=> "Visible on Hover",
"tempera_fpslider_bordersize"	=> "0",
"tempera_fpslider_topmargin"	=> "0",

"tempera_slideType"		=> "Custom Slides",
"tempera_slideCateg"	=> "",
"tempera_slideNumber"	=> "5",
"tempera_slideSpecific"	=> "",

"tempera_sliderimg1"	=> get_template_directory_uri()."/images/slider/tempera-slide1.jpg",
"tempera_slidertitle1"	=> "Jump right in!",
"tempera_slidertext1"	=> "It's like plunging into the calm ocean, the wind softly caressing your tanned body, the sun warming and igniting it. It's like feeling the ocean cool and
						embrace and contain you like a primordial womb. It's also like waking up from this dream and getting back to your blog!",
"tempera_sliderlink1"	=> "",
"tempera_sliderimg2"	=> get_template_directory_uri()."/images/slider/tempera-slide2.jpg",
"tempera_slidertitle2"	=> "Tempera brings the mountain to you",
"tempera_slidertext2"	=> "Remember that mountain you've always wanted to climb? Tempera will not only get it to come to you but it will also provide hiking equipment and if needed 
						will actually climb the mountain for you.",
"tempera_sliderlink2"	=> "",
"tempera_sliderimg3"	=> get_template_directory_uri()."/images/slider/tempera-slide3.jpg",
"tempera_slidertitle3"	=> "Using Tempera is a walk in the park",
"tempera_slidertext3"	=> "Using Tempera is really just a walk in the park. If in that park you'll meet a baby, using Tempera will become as easy as taking candy from that baby.
						If there's a picnic going on and there's cake, you can consider yourself invited and things will become a piece of cake.",
"tempera_sliderlink3"	=> "",
"tempera_sliderimg4"	=>  get_template_directory_uri()."/images/slider/tempera-slide4.jpg",
"tempera_slidertitle4"	=> "Tempera lives up to your expectations",
"tempera_slidertext4"	=> "Especially if your expectations are fluffy clouds. In that case it may even surpass your expectations; then your expectations will start having 
						expectations of their own which of course Tempera will be able to fulfil as well.",
"tempera_sliderlink4"	=> "",
"tempera_sliderimg5"	=>  get_template_directory_uri()."/images/slider/tempera-slide5.jpg",
"tempera_slidertitle5"	=> "Tempera is a breath of fresh air",
"tempera_slidertext5" 	=> "It's like being on a frozen mountain top. It's like getting there and not being able to climb back down. It's like having to survive in that hostile
						environment for months just by eating insects and drinking tea made out of twigs.",
"tempera_sliderlink5"	=> "",

"tempera_coldisplay"	=> "0",
"tempera_nrcolumns"		=> "3",
"tempera_columnNumber"	=> "3",
"tempera_colimageheight"	=> "201",
"tempera_colimagewidth"		=> "318",
"tempera_columnreadmore"	=> "Read more",
"tempera_columnType"	=> "Widget Columns",
"tempera_columnCateg"	=> "",
"tempera_columnSpecific"	=> "",

"tempera_fronttext1"	=> "Tempera is living on the edge, waiting for you to come and give it a push!",
"tempera_fronttext3"	=> "Above and below the columns you have editable titles and text fields. The text fields suppport <em>HTML</em> tags and [shortcodes] so you can turn the 
							Presentation Page into your personal playground. You can add, remove and edit all this and much more from the Tempera Settings page.<br>
							While you can show your latest posts on the Presentation Page, you can also use the <u>Blog</u> page template to designate another page as your primary
							blog posts page.<br><br>
							<div style='text-align:center;'><strong>As you can see, with Tempera the sky's the limit. Just remember to have fun!</strong></div>",
"tempera_fronttext2"	=> "",						
"tempera_fronttext4"	=> "",

"tempera_fronthideheader"	=> "",
"tempera_fronthidemenu"		=> "",
"tempera_fronthidewidget"	=> "",
"tempera_fronthidefooter"	=> "",
"tempera_fronthideback"		=> "",

"tempera_hheight"	=> "120",
"tempera_hcenter"	=> 0,
"tempera_hratio"	=> 0,

"tempera_logoupload"	=> "",
"tempera_favicon"		=> "",
"tempera_siteheader"	=> "Site Title and Description",
"tempera_headermargintop"	=> "40",
"tempera_headermarginleft"	=> "0",
"tempera_headerwidgetwidth" => "33%",

"tempera_fontfamily"	=> 'Ubuntu',
"tempera_googlefont"	=> '',
"tempera_fontsize"		=> "15px",
"tempera_fonttitle"		=> 'Yanone Kaffeesatz Regular',
"tempera_googlefonttitle"	=> '',
"tempera_headfontsize"	=> "34px",
"tempera_fontside"		=> 'Open Sans Light',
"tempera_googlefontside"	=> '',
"tempera_sidefontsize"		=> "18px",
"tempera_sitetitlefont"	=> 'Yanone Kaffeesatz Regular',
"tempera_sitetitlegooglefont"	=> '',
"tempera_sitetitlesize"	=> "38px",
"tempera_menufont" 		=> 'Droid Sans',
"tempera_menugooglefont"	=> '',
"tempera_menufontsize"	=> "14px",
"tempera_headingsfont"	=> 'Open Sans Light',
"tempera_headingsgooglefont"	=> '',
"tempera_headingsfontsize"	=> '120%',

"tempera_textalign"		=> "Default",
"tempera_paragraphspace"	=> "1.0em",
"tempera_parindent"		=> "0px",
"tempera_headingsindent"	=> "Disable",
"tempera_lineheight"	=> "1.7em",
"tempera_wordspace"		=> "Default",
"tempera_letterspace"	=> "Default",
"tempera_uppercasetext"	=> 0,

"tempera_colorschemes"	=> "Tempera Light",

"tempera_backcolorheader"	=> "",
"tempera_backcolormain"		=> "#171717",
"tempera_backcolorfooterw"	=> "",
"tempera_backcolorfooter"	=> "#F7F7F7",

"tempera_contentcolortxt"	=> "#444444",
"tempera_contentcolortxtlight"	=> "#999999",
"tempera_footercolortxt"	=> "#AAAAAA",

"tempera_titlecolor"	=> "#1693A5",
"tempera_descriptioncolor"	=> "#999999",
"tempera_descriptionbg"	=> "",

"tempera_menucolorbgdefault"	=> "#EAEAEA",
"tempera_menucolortxtdefault"	=> "#333333",
"tempera_submenucolorbgdefault"	=> "#2D2D2D",
"tempera_submenucolortxtdefault"	=> "#BBBBBB",
"tempera_submenucolorshadow"		=> "",

"tempera_topbarcolorbg"	=> "#000000",
"tempera_topmenucolortxt"	=> "#CCCCCC",
"tempera_topmenucolortxthover"	=> "#EEEEEE",

"tempera_contentcolorbg" 	=> "#FFFFFF",
"tempera_contentcolortxttitle"	=> "#444444",
"tempera_contentcolortxttitlehover"	=> "#000000",
"tempera_contentcolortxtheadings"	=> "#444444",

"tempera_sidebg"	=> "",
"tempera_sidetxt"	=> "#333333",
"tempera_sidetitlebg"	=> "#F7F7F7",
"tempera_sidetitletxt"	=> "#666666",

"tempera_widgetbg"		=> "",
"tempera_widgettxt"		=> "#333333",
"tempera_widgettitlebg"		=> "#F7F7F7",
"tempera_widgettitletxt"	=> "#666666",

"tempera_linkcolortext"		=> "#1693A5",
"tempera_linkcolorhover"	=> "#D6341D",
"tempera_linkcolorside"		=> "",
"tempera_linkcolorsidehover"	=> "",
"tempera_linkcolorwooter"	=> "",
"tempera_linkcolorwooterhover"	=> "",
"tempera_linkcolorfooter"	=> "",
"tempera_linkcolorfooterhover"	=> "",

"tempera_socialcolorbg"	=> "#1693A5",
"tempera_socialcolorbghover"	=> "#D6341D",

"tempera_metacoloricons"	=> "#CCCCCC",
"tempera_metacolorlinks"	=> "#666666",
"tempera_metacolorlinkshover"	=> "",

"tempera_accentcolora"	=> "#1693A5",
"tempera_accentcolorb"	=> "#D6341D",
"tempera_accentcolorc"	=> "#EEEEEE",
"tempera_accentcolord"	=> "#CCCCCC",
"tempera_accentcolore"	=> "#F7F7F7",

"tempera_fronttitlecolor"	=> "#444444",
"tempera_fpsliderbordercolor"	=> "#ffffff",
"tempera_fpslidercaptioncolor"	=> "#ffffff",
"tempera_fpslidercaptionbg"	=> "#000000",

"tempera_topbar"		=> "Normal",
"tempera_topbarwidth"	=> "Site width",
"tempera_breadcrumbs"	=> "Enable",
"tempera_pagination"	=> "Enable",
"tempera_menualign"		=> "left",
"tempera_contentmargintop" => "20",
"tempera_contentpadding" => "30",
"tempera_caption"		=> "caption-dark",
"tempera_image_style"	=> "tempera-image-one",
"tempera_contentlist"	=> "Show",
"tempera_title"		=> "Show",
"tempera_pagetitle"	=> "Show",
"tempera_categtitle"	=> "Show",
"tempera_tables"	=> "Disable",
"tempera_backtop"	=> "Enable",
"tempera_comtext"	=> "Show",
"tempera_comclosed"	=> "Hide everywhere",
"tempera_comoff"	=> "Show",

"tempera_metapos"	=> "Bottom",
"tempera_blog_show"	=> array(
	"comments"	=> 1,
	"date"		=> 1,
	"time"		=> 0,
	"author"	=> 1,
	"category"	=> 1,
	"tag"		=> 1,
	),
"tempera_single_show" => array(
	"date"		=> 1,
	"time"		=> 0,
	"author"	=> 1,
	"category"	=> 1,
	"tag"		=> 1,
	"bookmark"	=> 1,
),
"tempera_excerpthome"		=> "Excerpt",
"tempera_excerptsticky"		=> "Full Post",
"tempera_excerptarchive"	=> "Excerpt",
"tempera_excerptwords"		=> "50",
"tempera_magazinelayout"	=> "Disable",
"tempera_excerptdots"		=> " &hellip;",
"tempera_excerptcont"		=> "Continue reading",
"tempera_excerpttags"		=> "Disable",

"tempera_fpost" 	=> "Enable",
"tempera_fpostlink" => "1",
"tempera_fauto" 	=> "Enable",
"tempera_falign" 	=> "Left",
"tempera_fwidth" 	=> "250",
"tempera_fheight" 	=> "150",
"tempera_fcrop" 	=> "",
"tempera_fheader" 	=> "Disable",

"tempera_social1" 			=> "YouTube",
"tempera_social2" 			=> "#",
"tempera_social_title1" 	=> "",
"tempera_social_target1" 	=> "1",
"tempera_social3" 			=> "Twitter",
"tempera_social4" 			=> "#",
"tempera_social_title3" 	=> "",
"tempera_social_target3" 	=> "1",
"tempera_social5" 			=> "RSS",
"tempera_social6"			=> "#",
"tempera_social_title5" 	=> "",
"tempera_social_target5" 	=> "1",
"tempera_social7" 			=> "",
"tempera_social8" 			=> "",
"tempera_social_title7" 	=> "",
"tempera_social_target7" 	=> "1",
"tempera_social9" 			=> "",
"tempera_social10" 			=> "",
"tempera_social_title9" 	=> "",
"tempera_social_target9" 	=> "1",

"tempera_socialsdisplay0" => "1",
"tempera_socialsdisplay1" => "",
"tempera_socialsdisplay2" => "",
"tempera_socialsdisplay3" => "1",
"tempera_socialsdisplay4" => "",
"tempera_socialsdisplay5" => "1",

"tempera_postboxes" => '',
"tempera_copyright"	=> "This text can be changed from the Miscellaneous section of the settings page. <br />
<b>Lorem ipsum</b> dolor sit amet, <a href='#'>consectetur adipiscing</a> elit, cras ut imperdiet augue. ",
"tempera_customcss"	=> "/* Tempera Custom CSS */  ",
"tempera_customjs"	=> "",
"tempera_iecompat"	=> 0);


// Default column text						 
$tempera_column_defaults= array(
	$tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column1.jpg",
        'title'	=> 'Fully customizable',
        'text'	=> 'No need to edit files or learn to program, everything you want to change is just a mouse click away with a plethora of theme settings.
							If you like to get your hands dirty though, child themes are also fully supported.',
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank'	=> 1,
    ),
    $tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column2.jpg",
        'title'	=> 'Responsive',
        'text'	=> "Tablets, phones, iThings and Androids, portrait and landscape modes -  Tempera will take the shape of its container and will fit anywhere. 
							Just like an internet cat.",
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank'	=> 1,
    ),
	$tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column3.jpg",
        'title'	=> 'Endless Fonts ',
        'text'	=> "Tempera comes bundled with a huge array of great fonts, but it also supports Google fonts. Just type the font name in the theme settings and you're set.",
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank' => 1,
    ),
    $tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column4.jpg",
        'title'	=> 'Layouts and Page Templates',
        'text'	=> "Defy confinement! Everything should be where you want it to be, how you want it to be.Resize and rearrange the content and sidebars to your liking. 
							'Magazine' and 'Bog' layouts are also just around the corner.",
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank'	=> 1,
    ),
    $tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column5.jpg",
        'title'	=> 'Presentation Page',
        'text'	=> "It may seem pretty peculiar presenting the Presentation Page while presently peering at the Presentation Page itself. But it's worth mentioning that everything you see: titles, text, slides, animations, columns and more are all editable via the theme settings.",
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank' => 1,
    ),
    $tempera_column_content[] = array (
        'image'	=> get_template_directory_uri()."/images/columns/tempera-column6.jpg",
        'title'	=> 'HTML5, CSS3 and more',
        'text'	=> "Tempera can hold an unlimited amount of columns and we could've filled them all with more perks and features but we choose to leave something to your imagination.",
        'link'	=> 'http://www.cryoutcreations.eu',
        'blank' => 1,
    ),
);
?>